.PHONY: logistics_system_noetic_cuda11.7

all: logistics_system_noetic_cuda11.7


logistics_system_noetic_cuda11.7:
	docker build -t mzahana/logistics_system_noetic_cuda11.7 . -f Dockerfile_logistics_system-noetic-cuda-11.7.1

